CREATE TABLE jokers(
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(20) NOT NULL,
	email VARCHAR(100) NOT NULL,
	smile VARCHAR(100) NOT NULL,
	PRIMARY KEY(id),
	INDEX(email)
)	ENGINE=InnoDB AUTO_INCREMENT=1; 
 
