CREATE TABLE mail_act(
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(20) NOT NULL,
	token VARCHAR(100) NOT NULL,
	resource VARCHAR(50) NOT NULL,
	time VARCHAR(12) NOT NULL,
	PRIMARY KEY(id),
	INDEX(username)
)	ENGINE=InnoDB AUTO_INCREMENT=1; 
 